//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTOVENTAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocPaga
    {
        public DocPaga()
        {
            this.PAGO = new HashSet<PAGO>();
        }
    
        public int documentopaga { get; set; }
        public string descri { get; set; }
    
        public virtual ICollection<PAGO> PAGO { get; set; }
    }
}
