//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTOVENTAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_categoria
    {
        public tb_categoria()
        {
            this.tb_producto = new HashSet<tb_producto>();
        }
    
        public int CategoriaId { get; set; }
        public string descCategoria { get; set; }
    
        public virtual ICollection<tb_producto> tb_producto { get; set; }
    }
}
