//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTOVENTAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_venta
    {
        public tb_venta()
        {
            this.tb_ventaxproducto = new HashSet<tb_ventaxproducto>();
        }
    
        public int idVenta { get; set; }
        public int idUsuario { get; set; }
        public System.DateTime fechaVenta { get; set; }
        public bool estadoVenta { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
        public virtual ICollection<tb_ventaxproducto> tb_ventaxproducto { get; set; }
    }
}
